project:
  type: book


book:
  title: "Spatial Regression"
  subtitle: "A Practical Introduction"
  author: "Benjamin Reese, Parushya, Sarah Hayes"
  date: "12/12/2022"
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - chapter4.qmd
    - references.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

