project:
  type: book


book:
  title: "Spatial Regression"
  subtitle: "For PPOL670"
  author: "Benjamin Reese, Parushya, Sarah Hayes"
  date: "12/12/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter2-spatial-viz.qmd
    - part: chapter-3-spatial-autocorrelation-understanding.qmd
      chapters: 
        - chapter-3-1-sac-moran.qmd
    - chapter-4-modelling.qmd
    - chapter-5-adv-srm.qmd
    - chpater-6-applied-example.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

